
default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: golp_development

test:
  <<: *default
  database: golp_test

production:
  <<: *default
  database: golp_production

